import requests


def generate_business_report(
    insights: str,
    report_style: str = "Executive Summary",
    model: str = "llama3.2:1b",
) -> str:
    """
    Generate a professional business report from structured insights
    using a local Ollama model.

    The default model is a lightweight local model to reduce memory usage
    and improve compatibility on machines with limited RAM.

    Parameters
    ----------
    insights : str
        Structured business insights generated by the analytics pipeline.
    model : str, optional
        Name of the local Ollama model to use.

    Returns
    -------
    str
        AI-generated executive business report.
    """

    prompt = f"""
You are a senior business analyst.

Write a concise and professional {report_style} based on the following business insights.

The report should be clear, structured, and written for business stakeholders.

Use this structure:
- Executive Summary
- Key Performance Insights
- Risks or Declines
- Growth Drivers
- Recommended Next Actions

Business Insights:
{insights}
"""

    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
        timeout=120,
    )

    response.raise_for_status()

    result = response.json()

    return result["response"]

def generate_fallback_report(insights: str, report_style: str = "Executive Summary") -> str:
    """
    Generate a simple report without using an AI model.
    This is used when Ollama is not available.
    """

    return f"""
{report_style}

Overview
This report summarizes the key business performance results based on the available sales data.

Key Insights
{insights}

Recommended Next Actions
- Review declining revenue trends and identify the cause.
- Focus on the strongest performing category and region.
- Investigate the lowest performing category for improvement opportunities.
- Monitor weekly and monthly growth rates regularly.
"""